/**
 * Create axios response util returns the same object graph
 * as a response generated by Axios.
 *
 * @param {any} data Mock response data.
 * @param {any} requestData Optional. Mock request data.
 * @return {any} AxiosResponse object with supplied data
 */
function createAxiosResponse(data, requestData = {}) {
  return {
    data: data,
    status: 200,
    statusText: 'OK',
    headers: {},
    config: {},
    request: {...requestData}
  };
}

/**
 * Async create axios response util returns the same object graph
 * as a response generated by Axios. This util wraps response object in
 * a Promise.
 *
 * @param {any} data Mock response data.
 * @param {any} requestData Optional. Mock request data.
 * @return {any} AxiosResponse object with supplied data
 */
async function asyncCreateAxiosResponse(data, requestData = {}) {
  return new Promise((resolve) => {
    return resolve(createAxiosResponse(data, requestData));
  });
}

module.exports = {
  createAxiosResponse: createAxiosResponse,
  asyncCreateAxiosResponse: asyncCreateAxiosResponse
};
